# Configuracion en YAML para el Pipeline CI/CD

name: Integracion Continua / Entrega Continua

# Tres opciones de DESPARADORES
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# Inicio del trabajo
jobs:
  crearArtefacto:
    # implementacion sobre Ubuntu
    runs-on: ubuntu-latest
    # pasos
    steps:
      # lista de pasos del trabajo
      - name: Checkout del repositorio
        uses: actions/checkout@v2
      
      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Ejecutar script Python
        run: python .github/workflows/test_unitario.py  # test de programa1.py


      # Copiar el archivo programa1.py al directorio de artefactos
      - name: Copiar programa1.py al directorio de artefactos
        run: cp programa1.py $GITHUB_WORKSPACE/programa1.py

      # Guardar el archivo programa1.py como un artefacto con nombre progArtefacto
      - name: Guardar programa1.py como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: progArtefacto  
          path: $GITHUB_WORKSPACE/programa1.py 



          

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
