print (' ')
print ('*********************************************')
print ('*  Universidad Nacional Federico Villareal  *')
print ('*********************************************')
print ('  ')
print ('  simulacion de prueba unitaria ')
print (' ')

print ('========================= test sesion starts =========================')
print ('platform win32 -- Python 3.9.10, pytest-7.2.0, pluggy-1.0.0 --  ...')
print ('cachedir: .pytest_cache')
print ('collect 5 item')
print (' ')
print ('test_unitario.py::testeoMetodo1  PASSED                     [ 20%]')
print ('test_unitario.py::testeoMetodo2  PASSED                     [ 40%]')
print ('test_unitario.py::testeoMetodo3  PASSED                     [ 60%]')
print ('test_unitario.py::testeoMetodo4  PASSED                     [ 80%]')
print ('test_unitario.py::testeoMetodo5  PASSED                     [100%]')
print (' ')
print ('========================= 5 passed in 1.02s ==========================')